### PR TITLE
Add Dark Mode

### PR DESCRIPTION
**Pull request by jonas-lomholdt**
This is the PR you didn't know you wanted! It adds a new (highly opinionated) dark mode functionality using the `prefers-color-scheme` CSS media feature. The preference is automagically picked up via the settings in the operating system.

image

image

image

image

### CODE REVIEW

**Comment by PolygeneLubricants** [comment]
I love it! Let's run it on Nightly for a little while to experiment, and then I'll merge it.

**Comment by PolygeneLubricants** [comment]
The lights have now been turned off on nightly.justplanningpoker.com (how appropriate!).

image

**Comment by jonas-lomholdt** [comment]
Awesome! I may have removed a `bg-light` class on the nav header, that I noticed had a ever so slight gray background. On my screen at home I couldn't see the difference from white. I might need to add it back and override that specific class in the dark mode. Other than that the light mode should be unaffected :)

**Comment by PolygeneLubricants** [comment]
I didn't notice it either. In fact, I think it looks better without it. Let's keep it.

**Pull request merged**
